### ISSUE TITLE
Show picture of the year competition in the app?

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/campaigns#1]
v.2.10.0 is live for beta users and I was wondering if we should show the banner for this competition in the app? 

https://commons.wikimedia.org/wiki/Commons:Picture_of_the_Year/2018/R1/Gallery

**Comment by nicolas-raoul** [comment]
It is not a currently running photography competition, in the sense that a picture that I take right now will not be able to enter the competition, but I would be in favour of using it as an opportunity to test the app :-)

**Comment by nicolas-raoul** [comment]
Works great!

wow that campaign's website looks really bad on mobile :'-/
I guess evaluating pictures on a small screen is not a good idea in the first place.

I hope the webpages for competitions that force people to go out will look better on mobile... if not let's complain to them ^_^
wikilovesearth.org and https://www.wikilovesmonuments.org/contest/ look great on mobile :-)

**Comment by maskaravivek** [comment]
> It is not a currently running photography competition, in the sense that a picture that I take right now will not be able to enter the competition, but I would be in favour of using it as an opportunity to test the app

Yes, The banner is generic enough to show any content. IMO we should use it for any news/campaigns/competitions and not just for photo upload contests.
