### ISSUE TITLE
Mention the Wikipedia Pages Wanting Photos campaign?

### ISSUE THREAD

**Issue by sivaraam** [commons-app/campaigns#17]
The [Wikipedia Pages Wanting Photos campaign](https://meta.wikimedia.org/wiki/Wikipedia_Pages_Wanting_Photos) is in progress (1st July to August 31st 2020). Its about using the images uploaded to Commons on Wikipedia articles. I realize we usually add campaigns only related to uploading images but I thought this would be a useful campaign to advertise as it might motivate the users to use the images they upload to corresponding Wikipedia articles.

Its a nice co-incidence that we just recently implemented the "[use image uploaded via Nearby in Wikipedia article](https://github.com/commons-app/apps-android-commons/issues/872)" feature. :)

Thoughts?

**Comment by domdomegg** [comment]
Yes, this sounds good - happy to raise a PR if nobody objects.

**Comment by misaochan** [comment]
Sounds good. :) I will note that https://github.com/commons-app/apps-android-commons/issues/872 is in master but not in release, though, so most users won't have access to it.

**Comment by sivaraam** [comment]
Done in #18
